default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: mysql8_container
  timeout: 5000

development:
  <<: *default
  username: root
  password: vF$vy6wv
  database: react_app_database
